### PR TITLE
use generic separator (path.sep) instead of `/` char

### PR DESCRIPTION
**Pull request by salimkayabasi**

### CODE REVIEW

**Comment by minorgod** [comment]
That's funny, I submitted a very similar pull request a day ago, but I only changed the path separator in one place because I was working on making this compatible with Gulp 4 on Windows and when I changed the separator in the other places it broke the subtasks. I thought that was weird, but I didn't look into it further before submitting my pull request. On further reflection I think I realize the problem -- the currentPath var contains the path with the OS path separator, but in the unit tests the opts.dir is being passed in using a hardcoded forward slash, so when I changed all the functions to use the generic path.sep without updating the tests, it made them fail in windows. So, I'm guessing your pull request is the proper solution, but the tests should probably also be updated to use the generic path.sep wherever they use an options object with a custom dir.

**Comment by minorgod** [comment]
Actually, on even further reflection, I think this may be a better solution because it doesn't require changing unit tests or padding in a dir option using the os-specific path.sep:
https://github.com/minorgod/gulp-task-loader/commit/f51c9032c9c301b2b33908c064d1aa164b6c538a

**Comment by salimkayabasi** [comment]
As you say this PR is so similiar to yours. I had less time to add more tests for a better PR.
This module was breaking our CI configuration and I had to fix it ASAP.

Now in our projects we are using [this version](https://github.com/salimkayabasi/gulp-task-loader/releases/tag/windows-patch) of this module

**Comment by hontas** [comment]
Hey @salimkayabasi sorry bout the late reply. please remove the .*ignore-files from pull request - then i'll merge

**Comment by salimkayabasi** [comment]
Hi @hontas, thanks for warning me about that. I've just updated this PR  and sent another one for ignored files.

**Pull request merged**
