### PR TITLE
Enable sharing data or configurations between tasks, passing options to every independent task for reusage

### PR DESCRIPTION
**Pull request by aispin**
### Enable sharing data or configurations between tasks

Sometimes we need to share data or configurations between tasks.
I added some codes to implement this feature.
### How to use

For example, we can pass package.json to every single task now.

In gulpfile.js

```
var pkg = require('./package.json');
require('gulp-task-loader')({pkg: pkg});
```

In `gulp-tasks/xxx.js`, we can access `pkg` as below:

```
module.exports = function() {
    console.log( this );
        //access to the package.json
        console.log( this.opts.pkg );
        // reuse gulp object
        console.log( this.gulp );
};
```

### CODE REVIEW

**Comment by hontas** [comment]
Thank you for contributing!
First off, I see the benefit of being able to pass stuff like gulp and config, but how would you benefit from always passing `dependencies` and `taskName`?

And a couple of wishes...
1. Keep the syntax of the original code - tabs/spaces/indents etc.
2. Move `opts-test.js` into its own sub-folder under `test/` so that it has the same structure as the other tests and place the test last
3. Make the test a bit more inclusive - for example test what you describe above
4. Update the `README` with documentation on how to use this (use the text above if you wish)

**Comment by aispin** [comment]
@hontas 
Done! Pls check it out.

**Comment by hontas** [comment]
@mamboer thanks again for contributing!

**Comment by aispin** [comment]
@hontas My pleasure for the Open Source and human race. ^_^

**Pull request merged**
