### PR TITLE
Add option to filter out files by callback function

### PR DESCRIPTION
**Pull request by finwe**
This is useful eg. on Mac with Samba, which creates `.js` files beginning with a dot as backup. These files then prevent the plugin from functioning.

### CODE REVIEW

**Comment by hontas** [comment]
Hi sorry for slow feedback - been busy. I'll take a look after work ;) - thanks for contributing.

**Comment by hontas** [comment]
@finwe Could you please provide some more input to why the extensions filter is not good enough? I was trying to find something on samba and .js files - maybe you could point me in the right direction. Or is this something you can handle in samba.conf?

**Comment by finwe** [comment]
The extension filter is not good enough because these files always copy the original file name including the extension. The plugin will then fail on unexpected token.

@hontas Please see [this StackExchange question and answer](https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them).

Basically, these files are system metadata <del>for samba files</del> and as far as to what I have found they cannot be avoided <add>especially with mac and samba</add>.

**Comment by hontas** [comment]
@finwe In one of the comments to the top answer there is someone saying it's configurable. So unless you have another use case than this I'm gonna be a bit anal and close this for now.. until you convince me ;)
Reading about samba I also didn't find any info on `.js`-files being created. Are you sure the `extensions`-option isn't good enough?

**Comment by finwe** [comment]
Oh come on.

Another use case: I want to have both .js tasks and configuration .js files for them in the same directory. Configuration files export only a javascript object. This causes the plugin to fail:

```
gulp.task(taskName, dependencies, func.bind(context));
                                               ^

TypeError: func.bind is not a function
    at loadTask (/home/finwe/bubble/scarlet/node_modules/gulp-task-loader/index.js:54:42)
    at loadTasks (/home/finwe/bubble/scarlet/node_modules/gulp-task-loader/index.js:66:4)
```

With this change, I could ignore the configuration files and let the modules load normally.

**Pull request closed without merging**
