### PR TITLE
allow for the loading of infinitely nested children

### PR DESCRIPTION
**Pull request by timcosta**
This PR allows the plugin to load tasks from subfolders with more than one level of nesting.

### CODE REVIEW

**Comment by hontas** [comment]
thank you @tjsail33 for contributing. please adjust your whitespace settings so that you are using the same as the project. then ping me and i'll review your pull request. cheers.

**Comment by timcosta** [comment]
@hontas taken care of. thanks!

**Comment by hontas** [comment]
@tjsail33 looking good! and sorry bout the late reply. There is one line with extraneous (hope I spelled that one right) in ìndex.js`line 64 and above that - please update the README so that the documentation is up to date.

**Comment by timcosta** [comment]
@hontas the extraneous tabs have been removed, and the README has been updated to mention the usage of nested folders.

**Comment by timcosta** [comment]
Thanks @hontas!

**Pull request merged**
